"""refining models, creating a many-to-many for comments and users

Revision ID: 282b7f9ee19b
Revises: d9de29915e5a
Create Date: 2022-08-17 13:14:08.315531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282b7f9ee19b'
down_revision = 'd9de29915e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_liked_comments',
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['thread_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['forum_users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_liked_comments')
    # ### end Alembic commands ###
