"""Refining models

Revision ID: 34ff9e143d8e
Revises: 
Create Date: 2022-08-13 21:15:52.072507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ff9e143d8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('role', sa.Enum('simple_user', 'manager', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('forum_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('role', sa.Enum('simple_user', 'manager', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.Enum('no_category', 'gaming', 'movies', 'books', 'politics', 'social_media', 'tech_help', name='threadcategories'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attachment', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='threadstate'), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('forum_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['forum_user_id'], ['forum_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('forum_user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['forum_user_id'], ['forum_users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_comment')
    op.drop_table('threads')
    op.drop_table('forum_users')
    op.drop_table('forum_managers')
    # ### end Alembic commands ###
