"""Refinind donation models

Revision ID: 90677735fbe4
Revises: deadf813bdad
Create Date: 2022-08-22 23:02:08.449772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90677735fbe4'
down_revision = 'deadf813bdad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threads', 'attachment',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threads', 'attachment',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###
