"""refining comment model

Revision ID: e196d34b8381
Revises: b58c9d6f658b
Create Date: 2022-08-15 14:53:31.007314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e196d34b8381'
down_revision = 'b58c9d6f658b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_comment', sa.Column('attachment', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread_comment', 'attachment')
    # ### end Alembic commands ###
