"""refining comment model

Revision ID: e7952e39bf91
Revises: e196d34b8381
Create Date: 2022-08-15 15:02:09.941702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7952e39bf91'
down_revision = 'e196d34b8381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_comment', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread_comment', 'created_on')
    # ### end Alembic commands ###
